# Site settings
title:          dg
description:    "digiexe-official Coupons and Promo Codes for 2025"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         digiexe-official
  url:          https://digiexe-official.com
  email:        digiexe-official@gmail.com

# Build settings
remote_theme: chesterhow/tale
markdown:       kramdown
include:
  - _pages
  - _posts
  - wp

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /pretty
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale